/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kase.aptechsaigon.javaproject;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author dev
 */
public class MainFrame extends javax.swing.JFrame {

    private static boolean isLogin; 
    private static final LoginFrame loginFrm = new LoginFrame();
    public static final MainFrame MainFrm = new MainFrame();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        mnuMain.setVisible(false);
        loginFrm.addWindowListener(getWindowAdapter());
    }
    
    public void SetPermission(boolean isLogin) {
        this.isLogin = isLogin;
        mnuMain.setVisible(isLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JScrollPane();
        mnuMain = new javax.swing.JMenuBar();
        mnuAcc = new javax.swing.JMenu();
        mnuMemberInfo = new javax.swing.JMenuItem();
        mnuChangPass = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuLogout = new javax.swing.JMenuItem();
        mnuHR = new javax.swing.JMenu();
        mnuSa = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuDept = new javax.swing.JMenuItem();
        mnuEmp = new javax.swing.JMenuItem();
        mnuPro = new javax.swing.JMenu();
        mnuTech = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuAcc.setText("Tài khoản");

        mnuMemberInfo.setText("Thông tin cá nhân");
        mnuMemberInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMemberInfoActionPerformed(evt);
            }
        });
        mnuAcc.add(mnuMemberInfo);

        mnuChangPass.setText("Thay đổi mật khẩu");
        mnuAcc.add(mnuChangPass);
        mnuAcc.add(jSeparator1);

        mnuLogout.setText("Đăng xuất");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        mnuAcc.add(mnuLogout);

        mnuMain.add(mnuAcc);

        mnuHR.setText("Nhân sự");

        mnuSa.setText("Bảng lương");
        mnuHR.add(mnuSa);
        mnuHR.add(jSeparator2);

        mnuDept.setText("Phòng ban");
        mnuHR.add(mnuDept);

        mnuEmp.setText("Nhân viên");
        mnuHR.add(mnuEmp);

        mnuMain.add(mnuHR);

        mnuPro.setText("Chương trình học");
        mnuMain.add(mnuPro);

        mnuTech.setText("Dạy học");
        mnuMain.add(mnuTech);

        setJMenuBar(mnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMemberInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMemberInfoActionPerformed
        // TODO add your handling code here:
        showChild(new UserFrame());
    }//GEN-LAST:event_mnuMemberInfoActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        // TODO add your handling code here:
        SetPermission(false);
        loginFrm.show();
    }//GEN-LAST:event_mnuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //var screen = Toolkit.getDefaultToolkit().getScreenSize();
        //frm.setSize((int)(screen.getWidth()), (int)(screen.getHeight()));
        
        MainFrm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        MainFrm.toFront();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrm.setVisible(true);
                
                if(!isLogin) {
                    loginFrm.show();
                }
            }
        });
    }
    
    private void showChild(JFrame child) {
        child.setExtendedState(JFrame.MAXIMIZED_BOTH);
        var childContent = child.getContentPane();
        this.setContentPane(childContent);
    }
    
    private WindowAdapter getWindowAdapter() {
        return new WindowAdapter() {
          @Override
          public void windowIconified(WindowEvent we) {
            loginFrm.setState(JFrame.NORMAL);
          }
        };
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuAcc;
    private javax.swing.JMenuItem mnuChangPass;
    private javax.swing.JMenuItem mnuDept;
    private javax.swing.JMenuItem mnuEmp;
    private javax.swing.JMenu mnuHR;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JMenuItem mnuMemberInfo;
    private javax.swing.JMenu mnuPro;
    private javax.swing.JMenuItem mnuSa;
    private javax.swing.JMenu mnuTech;
    private javax.swing.JScrollPane pnMain;
    // End of variables declaration//GEN-END:variables
}
